// Bu dosya, Firebase yapılandırma ayarlarını içerir ve FlutterFire CLI tarafından otomatik olarak oluşturulmuştur.
// Farklı platformlar için Firebase bağlantı bilgilerini ve API anahtarlarını yönetir.

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Mevcut platform için uygun Firebase yapılandırmasını döndürür
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android platformu için Firebase yapılandırma ayarları
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuztfsQyj50mqsYgXF_NbAfTZOKzbPvkA',
    appId: '1:375193215607:android:ec6cacbc4303c109dc9c72',
    messagingSenderId: '375193215607',
    projectId: 'voxure-app',
    storageBucket: 'voxure-app.firebasestorage.app',
  );

  // Web platformu için Firebase yapılandırma ayarları
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr2uRykZtWAdV_yGGXzXo2qjENB50CuJo',
    appId: '1:375193215607:web:130f3b33bd1d77dedc9c72',
    messagingSenderId: '375193215607',
    projectId: 'voxure-app',
    authDomain: 'voxure-app.firebaseapp.com',
    storageBucket: 'voxure-app.firebasestorage.app',
    measurementId: 'G-0W0Y7NE1C1',
  );

  // Windows platformu için Firebase yapılandırma ayarları
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr2uRykZtWAdV_yGGXzXo2qjENB50CuJo',
    appId: '1:375193215607:web:89696cc6866aabcbdc9c72',
    messagingSenderId: '375193215607',
    projectId: 'voxure-app',
    authDomain: 'voxure-app.firebaseapp.com',
    storageBucket: 'voxure-app.firebasestorage.app',
    measurementId: 'G-NQXZYM7Z3J',
  );
}